const products = [
    {
        _id: '1',
        name: 'Toy',
        image: './images/toy.jpg',
        description: '',
        brand: '',
        category: '',
        price: '',
        countInStock:'',
        rating: '',
        numReviews: '',
    },
    {
        _id: '2',
        name: 'Bed',
        image: './images/bed.jpg',
        description: '',
        brand: '',
        category: '',
        price: '',
        countInStock:'',
        rating: '',
        numReviews: '',
    },
    {
        _id: '3',
        name: 'Bowls',
        image: './images/bowls.jpg',
        description: '',
        brand: '',
        category: '',
        price: '',
        countInStock:'',
        rating: '',
        numReviews: '',
    },
    {
        _id: '4',
        name: 'Biscuits',
        image: './images/biscuits.jpg',
        description: '',
        brand: '',
        category: '',
        price: '',
        countInStock:'',
        rating: '',
        numReviews: '',
    },
    {
        _id: '5',
        name: 'House',
        image: './images/house.jpg',
        description: '',
        brand: '',
        category: '',
        price: '',
        countInStock:'',
        rating: '',
        numReviews: '',
    },
    {
        _id: '6',
        name: 'Mouth Cover',
        image: './images/mouthCover.jpg',
        description: '',
        brand: '',
        category: '',
        price: '',
        countInStock:'',
        rating: '',
        numReviews: '',
    },
    {
        _id: '7',
        name: 'Pedigree',
        image: './images/pedigree.jpg',
        description: '',
        brand: '',
        category: '',
        price: '',
        countInStock:'',
        rating: '',
        numReviews: '',
    }
]