const products = [
    {
        _id: '1',
        name: 'Toy',
        image: '/images/toy.jpg',
        description: 'JAINSONS PET PRODUCTS Dog Chew Knot Ball Woven Braided Rainbow Bouncy Rubber Toy with Jingle Bell Inside for Pet Training',
        brand: 'Jainson',
        category: 'Dog Toy',
        price: '25',
        countInStock:'8',
        rating: '4',
        numReviews: '4',
    },
    {
        _id: '2',
        name: 'Bed',
        image: '/images/bed.jpg',
        description: 'Slatters Be Royal Store Round Shape Reversible Dual Ultra Soft Ethnic Velvet Bed for Dog and Cat (Brown, XXL)',
        brand: 'Slatters',
        category: 'Dog ED',
        price: '35',
        countInStock:'4',
        rating: '4.5',
        numReviews: '3',
    },
    {
        _id: '3',
        name: 'Bowls',
        image: '/images/bowls.jpg',
        description: 'Naaz Pet Supplies Stainless Steel Anti Skid Dog Bowls Medium (450ml, Silver) - Set of 2',
        brand: 'Naaz',
        category: 'Dog Bowls',
        price: '10',
        countInStock:'6',
        rating: '4',
        numReviews: '4',
    },
    {
        _id: '4',
        name: 'Biscuits',
        image: './images/biscuits.jpg',
        description: 'Healthy Treats Himalaya Adult Dog Biscuits with Chicken Treat 1 Kg -Pack of 2',
        brand: 'Himalaya',
        category: 'Dog Biscuits',
        price: '40',
        countInStock:'2',
        rating: '4.5',
        numReviews: '5',
    },
    {
        _id: '5',
        name: 'House',
        image: './images/house.jpg',
        description: 'AmazonBasics Elevated Portable Pet House - Medium, Black',
        brand: 'Amazon basis',
        category: 'Dog House',
        price: '45',
        countInStock:'3',
        rating: '4',
        numReviews: '4',
    },
    {
        _id: '6',
        name: 'Mouth Cover',
        image: './images/mouthCover.jpg',
        description: 'MUNCHOS Adjustable High Quality Muzzle cum Mouth Cover / Basket Cage Collar for Dog For Extra Care - Large',
        brand: 'Munchos',
        category: 'Dog Mouth Cover',
        price: '10',
        countInStock:'0',
        rating: '4',
        numReviews: '3',
    },
    {
        _id: '7',
        name: 'Pedigree',
        image: './images/pedigree.jpg',
        description: 'Pedigree Adult Dry Dog Food (High Protein Variant) Chicken, Egg & Rice, 10kg Pack',
        brand: 'Pedigree',
        category: 'Dog food',
        price: '35',
        countInStock:'5',
        rating: '5',
        numReviews: '5',
    }
]

export default products;